FROM elixir:alpine
WORKDIR /backend

RUN mix local.hex --force && mix local.rebar --force

COPY backend/mix.exs backend/mix.lock ./
RUN mix do deps.get, deps.compile

COPY backend ./

EXPOSE 4000
CMD iex -S mix phx.server
