version: '3.3'

services:
  db:
    image: postgres:latest

  logic:
    build:
      context: .
      dockerfile: Dockerfile-logic.dev
    volumes:
      - ./src/logic:/logic
      - logic:/logic-output

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend.dev
    depends_on:
      - logic
    volumes:
      - ./src/frontend:/frontend
      - logic:/logic
      - frontend:/frontend-output

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend.dev
    ports:
      - 9000:9000
    depends_on:
      - db
      - logic
    volumes:
      - .:/backend
      - logic:/logic
      - frontend:/frontend
    # https://github.com/docker/compose/issues/596#issuecomment-133004835
    stdin_open: true

volumes:
  logic:
  frontend:
