FROM hseeberger/scala-sbt:8u222_1.3.4_2.13.1
WORKDIR /backend

COPY . ./
RUN sbt clean stage

EXPOSE 9000
CMD rm -rf /static/* && cp -r /tmp/static/* /static && \
    target/universal/stage/bin/robot-rumble \
        # https://stackoverflow.com/a/29244028
        -Dpidfile.path=/dev/null
