version: '3.7'

services:
  db:
    image: postgres:latest

  app:
    build: .
    environment:
      - COOKIE='abc'
      - NAME='robot'

    volumes:
      - ./backend:/backend
      - static:/static
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/static:ro
    depends_on:
      - app

volumes:
  static:
