FROM node:latest
WORKDIR /frontend

COPY src/frontend/package.json ./
RUN npm install

COPY src/frontend ./

# needed for elm to install packages
RUN node_modules/.bin/elm make src/*.elm

CMD npm run watch

