version: '3.7'

services:
  db:
    image: postgres:latest

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  app:
    build: .
    ports:
      - 4000
    environment:
      - COOKIE='abc'
    depends_on:
      - db
      - nginx
