FROM ocaml/opam2:latest AS logic-builder
WORKDIR /logic

COPY logic/logic.opam ./
RUN opam pin add -yn logic ./
RUN opam depext logic
RUN opam install --deps-only logic

COPY logic ./

# required for dune watch
RUN sudo apt-get update && sudo apt-get install -y inotify-tools

RUN sudo mkdir /logic-output
RUN sudo chown -R opam:nogroup /logic-output
CMD dune build @frontend -w --build-dir=/logic-output/_build

