on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 sync public/images s3://${{ secrets.S3_BUCKET_PUBLIC }}/images

      - uses: actions/setup-java@v1
        with:
            java-version: 1.8
      - run: sbt clean dist

      - run: wget https://files.boxfuse.com/com/boxfuse/client/boxfuse-commandline/1.33.0.1460/boxfuse-commandline-1.33.0.1460-linux-x64.tar.gz
      - run: tar xf boxfuse-commandline-1.33.0.1460-linux-x64.tar.gz
      - run: ./boxfuse/boxfuse run 
          -user=${{ secrets.BOXFUSE_USER }} 
          -secret=${{ secrets.BOXFUSE_SECRET }} 
          -envvars.BATTLE_QUEUE_IN_URL=${{ secrets.BATTLE_QUEUE_IN_URL }} 
          -envvars.BATTLE_QUEUE_OUT_URL=${{ secrets.BATTLE_QUEUE_OUT_URL }} 
          -envvars.SECRET_KEY='${{ secrets.SECRET_KEY }}' 
          -envvars.ASSETS_PATH=${{ secrets.CLOUDFRONT_URL }}
          -jvm.args=-Ddb.default_.migration.auto=true
          -ports.http=80 
          -env=test
